[workspace]
members = ["starks-v2", "lang"]
resolver = "3"

[workspace.dependencies]
futures = "0.3.31"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.9"

